---
title: "Suporte técnico e difusão do uso SMAE"
---

## Suporte Técnico

Caso surjam dúvidas operacionais ou problemas técnicos, não hesite em enviar um e-mail para os três destinatários a seguir:

-   programademetas\@prefeitura.sp.gov.br

-   codata\@prefeitura.sp.gov.br

-   Ponto focal em CPMA

O e-mail deve conter:

-   Módulo de utilização;

-   Descrição detalhada do problema/dúvida;

-   Imagens ("print screen") ou vídeos da tela demonstrando o problema;

-   Número de telefone do requisitante;

## Difusão do uso do SMAE

Para saber mais sobre o Sistema de Monitoramento e Acompanhamento Estratégico (SMAE), conheça a sua [página institucional](https://smae.prefeitura.sp.gov.br/).

Além do módulo do Programa de Metas, no qual o monitoramento orçamentário objeto deste manual, é uma das etapas, o Sistema de Monitoramento e Acompanhamento Estratégico pode agregar valor ao seu órgão por meio de outros módulos:

-   Módulo de **Planos Setoriais**: para saber mais, contate: programademetas\@prefeitura.sp.gov.br

-   Módulo de **Gestão de Projetos**: para saber mais, contate: fabricioreis\@prefeitura.sp.gov.br
