---
title: "O que é o monitoramento orçamentário?"
---

O monitoramento orçamentário é o processo contínuo de acompanhamento e avaliação da execução orçamentária do Programa de Metas (PdM) da Prefeitura de São Paulo (PMSP). **Mas para que monitorar?**

Existem três razões principais:

|                   |                                                                                                                                                                                                                                                                                                                       |
|-------------------|-----------------------------------------------------|
| **Dimensão**      | **Descrição**                                                                                                                                                                                                                                                                                                         |
| **Gerencial**     | Garantir que os recursos orçamentários previstos sejam utilizados de forma eficiente e em consonância com as prioridades estabelecidas pela gestão municipal, possibilitando ajustes de rota sempre que necessário.                                                                                                   |
| **Governamental** | Garantir que as peças orçamentárias (Plano Plurianual - PPA; Lei de Diretrizes Orçamentárias - LDO e Lei do Orçamento Anual - LOA) compreendam as prioridades estabelecidas pela gestão municipal, possibilitando coerência administrativa e capacidade de planejamento e execução.                                   |
| **Transparência** | Informar a sociedade civil e os órgãos de controle, cumprindo as prerrogativas do [Art. 69-A, da Lei Orgânica do Município](https://legislacao.prefeitura.sp.gov.br/leis/lei-0-de-04-de-abril-de-1990) e do [Decreto 63.336/2024](https://legislacao.prefeitura.sp.gov.br/leis/decreto-63336-de-10-de-abril-de-2024). |

Sabemos que a tarefa de prover informações orçamentárias não é a mais simples. É, na verdade, muito trabalhosa. Mas por entendermos que ela cumpre funções em diferentes dimensões -- seja para subsidiar decisões do(a) Prefeito(a), seja para fomentar a transparência e o controle social --, queremos tornar esta tarefa tanto menos árdua quanto mais valiosa.

Vamos, então, falar sobre quem faz o que no monitoramento orçamentário do Programa de Metas?
